version: '3.9'

services:
  app:
    container_name: docker-nodejs
    restart: always
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mongo_db
  #mongo services
  mongo_db:
    container_name: mongodb-container
    image: mongo:6.0.3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}

    